name: Django CI

on: [ push ]

jobs:
  run-tests:
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: "Netflix.settings"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install Requirements
        working-directory: ./Netflix
        run: pip install -r requirements.txt
      - name: Database Migrate
        working-directory: ./Netflix
        run: python manage.py migrate
      - name: Run Tests
        working-directory: ./Netflix
        run: pytest

